- name: Create directory
  file:
    path: "{{ galaxy_subsite_dir }}"
    state: directory
    mode: 0755

- name: Template out main welcome page
  template:
    src: welcome.html
    dest: "{{ galaxy_subsite_dir }}/welcome.html"
    mode: 0644

- name: "Template out welcome pages"
  template:
    src: welcome.html
    dest: "{{ galaxy_subsite_dir }}/{{ item.name }}.{{ galaxy_subsite_base_domain }}.html"
    mode: 0644
  with_items: "{{ galaxy_subsites }}"

# Create the 'additional' CSS that's added to the base Galaxy CSS.
- name: Template out CSS files
  template:
    src: multisite-base.css
    dest: "{{ galaxy_subsite_dir }}/{{ item.name }}.{{ galaxy_subsite_base_domain }}-custom.css"
    mode: 0644
  with_items: "{{ galaxy_subsites }}"
  register: custom_css

- name: Template out CSS files
  copy:
    dest: "{{ galaxy_subsite_dir }}/{{ galaxy_subsite_base_domain }}-custom.css"
    content: "{{ galaxy_subsite_base_css }}"
    mode: 0644
  register: base_css

- name: Copy custom background images
  copy:
    src: "files/subsites/{{ item.name }}.png"
    dest: "{{ galaxy_subsite_dir }}/{{ item.name }}.png"
    mode: 0644
  with_items: "{{ galaxy_subsites }}"
  when: item.wallpaper | default(False)

- name: Main CSS
  shell: "cat {{ galaxy_server_dir }}/static/style/base.css {{ galaxy_subsite_dir }}/{{ galaxy_subsite_base_domain }}-custom.css > {{ galaxy_subsite_dir }}/{{ galaxy_subsite_base_domain }}.css"
  when: __galaxy_git_update_result is changed or (galaxy_subsite_base_css is defined and base_css is changed)


# Not sure why this is needed, to be honest. Should review.
- name: Main CSS replace background color
  replace:
    path: "{{ galaxy_subsite_dir }}/{{ galaxy_subsite_base_domain }}.css"
    regexp: '#masthead{background-color:#2c3143}' # Base galaxy masthead colouring
    replace: '#masthead{background-color:#003399}' # Our custom masthead colouring

# Make the final CSS files.
- name: Merge CSS files
  shell: "cat {{ galaxy_server_dir }}/static/style/base.css {{ galaxy_subsite_dir }}/{{ galaxy_subsite_base_domain }}-custom.css > {{ galaxy_subsite_dir }}/{{ item.name }}.{{ galaxy_subsite_base_domain }}.css"
  with_items: "{{ galaxy_subsites }}"
  when: __galaxy_git_update_result is changed or custom_css is changed
