- name: Create directory
  file:
    path: "{{ galaxy_subsite_dir }}"
    state: directory
    mode: 0755

- name: Template out main welcome page
  template:
    src: welcome.html
    dest: "{{ galaxy_subsite_dir }}/{{ galaxy_subsite_base_domain }}.html"
    mode: 0644

- name: "Template out welcome pages"
  template:
    src: welcome.html
    dest: "{{ galaxy_subsite_dir }}/{{ item.name }}.{{ galaxy_subsite_base_domain }}.html"
    mode: 0644
  with_items: "{{ galaxy_subsites }}"

- name: Template out custom CSS per subsite.
  template:
    src: multisite-base.css
    dest: "{{ galaxy_subsite_dir }}/{{ item.name }}.{{ galaxy_subsite_base_domain }}-custom.css"
    mode: 0644
  with_items: "{{ galaxy_subsites }}"

- name: Create base domain custom css
  copy:
    dest: "{{ galaxy_subsite_dir }}/{{ galaxy_subsite_base_domain }}-custom.css"
    content: "{{ galaxy_subsite_base_css }}"
    mode: 0644

# Any images
- name: Copy custom background images
  copy:
    src: "files/subsites/{{ item.name }}.png"
    dest: "{{ galaxy_subsite_dir }}/{{ item.name }}.png"
    mode: 0644
  with_items: "{{ galaxy_subsites }}"
  when: item.wallpaper | default(False)

# Main css file that's used as a fallback.
- name: Create main site CSS
  shell: "cat {{ galaxy_server_dir }}/static/style/base.css {{ galaxy_subsite_dir }}/{{ galaxy_subsite_base_domain }}-custom.css > {{ galaxy_subsite_dir }}/{{ galaxy_subsite_base_domain }}.css"

# Make the final CSS files.
- name: Merge CSS files for subsites
  shell: "cat {{ galaxy_server_dir }}/static/style/base.css {{ galaxy_subsite_dir }}/{{ galaxy_subsite_base_domain }}-custom.css > {{ galaxy_subsite_dir }}/{{ item.name }}.{{ galaxy_subsite_base_domain }}.css"
  with_items: "{{ galaxy_subsites }}"
